export interface UserInfo{
    registration_id ?:string;
    username ?:string;
    firstname ?:string;
    lastname ?:string;
    image_url ?:string;
    building ?:string;
    address1 ?:string;
    address2 ?:string;
    city ?:string;
    state ?:string;
    land_mark ?:string;
    pincode ?:string;
    country ?:string;
    phone ?:string;
    email ?:string;
    password ?:string;
    creditcard ?:string;
    creditcardtypeid ?:string;
    cardexpmo ?:string;
    cardexpyr ?:string;
    delivery_building ?:string;
    delivery_address ?:string;
    delivery_city ?:string;
    delivery_region ?:string;
    delivery_postal_code ?:string;
    delivery_country ?:string;
    acceptterm ?:string; 
    created_date ?:string; 
    created_time ?:string; 
    update_date ?:string; 
    update_time ?:string;
    status?:string;
}